#!/bin/bash

# Usage: Put this in torrc:
# ServerTransportPlugin obfs3_websocket exec /path/to/obfs-flash-server

: ${WEBSOCKET_SERVER:=websocket-server}
: ${OBFSPROXY:=obfsproxy}

# obfsproxy listens locally on this port and websocket-client connects to it as
# if it were an ORPort.
MID_PORT=2333

if [ "$TOR_PT_MANAGED_TRANSPORT_VER" != "1" ]; then
	echo VERSION-ERROR no-version
	exit 1
fi
echo VERSION 1

if [ "$TOR_PT_SERVER_TRANSPORTS" != "obfs3_websocket" -a "$TOR_PT_SERVER_TRANSPORTS" != "*" ]; then
	echo SMETHODS DONE
	exit 1
fi

if [ -z "$TOR_PT_ORPORT" ]; then
	echo ENV-ERROR missing TOR_PT_ORPORT
	exit 1
fi

if [ -z "$TOR_PT_SERVER_BINDADDR" ]; then
	echo ENV-ERROR missing TOR_PT_SERVER_BINDADDR
	exit 1
fi

BINDADDR=$(echo "$TOR_PT_SERVER_BINDADDR" | sed -e 's/.*-//')

trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT

env TOR_PT_MANAGED_TRANSPORT_VER=1 \
	TOR_PT_STATE_LOCATION="$TOR_PT_STATE_LOCATION" \
	TOR_PT_EXTENDED_SERVER_PORT="" \
	TOR_PT_ORPORT="$TOR_PT_ORPORT" \
	TOR_PT_SERVER_TRANSPORTS=obfs3 \
	TOR_PT_SERVER_BINDADDR="obfs3-127.0.0.1:$MID_PORT" \
	"$OBFSPROXY" managed > /dev/null &

env TOR_PT_MANAGED_TRANSPORT_VER=1 \
	TOR_PT_STATE_LOCATION="$TOR_PT_STATE_LOCATION" \
	TOR_PT_ORPORT="127.0.0.1:$MID_PORT" \
	TOR_PT_SERVER_TRANSPORTS=websocket \
	TOR_PT_SERVER_BINDADDR="websocket-$BINDADDR" \
	"$WEBSOCKET_SERVER" | gawk '/^SMETHOD / {print $1 " obfs3_websocket " $3; print "SMETHODS DONE"; fflush();}' &

wait %%
