#!/usr/bin/python

import os
import sys
import time

from pyptlib.util.subproc import auto_killall, Popen, SINK
from pyptlib.client import ClientTransportPlugin
from subprocess import PIPE

auto_killall(1)

def pt_child_env(env, managed_ver):
    """
    Prepare the environment for a child PT process, by clearing all TOR_PT_*
    envvars except TOR_PT_STATE_LOCATION and TOR_PT_MANAGED_TRANSPORT_VER.
    """
    exempt = ['TOR_PT_STATE_LOCATION']
    cur_env = [(k, v) for k, v in env.iteritems()
                      if not k.startswith('TOR_PT_') or k in exempt]
    cur_env.append(('TOR_PT_MANAGED_TRANSPORT_VER', ','.join(managed_ver)))
    return cur_env

ob_client = os.getenv("OBFSPROXY", "obfsproxy")
fp_client = os.getenv("FLASHPROXY_CLIENT", "flashproxy-client")
fp_local_port = int(os.getenv("FLASHPROXY_LOCAL_PORT", 9001))
fp_remote_port = int(os.getenv("FLASHPROXY_REMOTE_PORT", 9000))
mid_port = 2334

client = ClientTransportPlugin.fromEnv()
client.init(['obfs3_flash'])
cur_env = pt_child_env(os.environ, client.config.getManagedTransportVersions())

fp_proc = Popen(
    [fp_client, ":%s" % fp_local_port, ":%s" % fp_remote_port],
    stdout = SINK,
    env = dict(cur_env + {
        "TOR_PT_CLIENT_TRANSPORTS": "websocket",
    }.items()),
    )

mid_proc = Popen(
    ["socat",
     "TCP-LISTEN:%s,reuseaddr,fork,bind=127.0.0.1" % mid_port,
     "SOCKS4A:127.0.0.1:0.0.1.0:1,socksport=%s" % fp_local_port],
    stdout = SINK,
    )

ob_proc = Popen(
    [ob_client, "managed"],
    stdout = PIPE,
    env = dict(cur_env + {
        "TOR_PT_CLIENT_TRANSPORTS": "obfs3",
    }.items()),
    )

while 1:
    # readlines() has a stupid non-bypassable buffer which hangs everything
    line = ob_proc.stdout.readline()
    if not line: break
    # TODO(infinity0): add read/parse utilities to pyptlib for this
    (kw, args) = line.split(" ", 1)
    if kw == "VERSION":
        pass
    elif kw == "CMETHOD" and args.startswith("obfs3 "):
        (_, socks, addrstr) = args.split(" ", 2)
        socksVer = socks[5:]
        addrport = addrstr.split(":")
        client.reportMethodSuccess("obfs3_flash", socksVer, addrport)
    elif kw == "CMETHODS" and args == "DONE":
        client.reportMethodsEnd()
    else:
        pass
    sys.stdout.flush()

ob_proc.wait()
